# Generated by Django 5.0.6 on 2024-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('srollno', models.IntegerField()),
                ('sfees', models.IntegerField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
