# Generated by Django 5.0.6 on 2024-05-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_amazon'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sdob',
            field=models.DateField(null=True),
        ),
    ]
